language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  global:
    - CIRPY_TEST_DELAY=5
  matrix:
    - OPTIONAL_DEPS=true
    - OPTIONAL_DEPS=false
install:
  - pip install coveralls
  - if [ "$OPTIONAL_DEPS" = true ]; then pip install lxml; fi
script:
  - coverage run --source=cirpy setup.py test
after_success:
  - coveralls
